### ISSUE TITLE
作者辛苦了~

### ISSUE THREAD

**Issue by themis0009** [dingdangdog/cashbook#1]
运行SERVER，打开后闪退。
运行cashbook.exe，打开后空白，不知道在哪里操作。
========================
还是谢谢作者大大~
但是个人觉得，如果把SERVER放在DOCKER里面跑会不会更好一点？毕竟弱小可怜又无助的廉价VPS跑不动WINDOWS程序~_~
我不清楚以上说法是否科学合理，只是一个外行给出的一些简单看法。

作为一个账本，我个人觉得，第一应该是好用。但是我十几年来用过无数的账本工具，从小众的紫宸，到随大流的网易有钱。从简陋的EXCEL到功能齐全的随手记等等。它们各具特色，但是也都有一些缺点。

问题是，以上除了EXCEL，全都倒闭了（哭笑）。

EXCEL最大的优点是数据自己保存，任何地方任何软件，都不敢拍着胸脯大声说，我不支持EXCEL。所以这种数据，只要自己的硬盘不坏，任何时候都不会丢失。缺点是，不能离线，导致记性不好外加很懒的我，如果不能及时记下一笔收支，回头就忘了。记账本的功能更无从说起。

其它软件我用过的最好用是紫宸，但是貌似11年倒闭了。其次是网易有钱，18年倒闭了。

后来用过一羽等，平心而论，挺好用。但是缺点很明显：数据加密。这些软件都有一个巨大的问题就是导出的数据库都是加密的，或者至少是比较独有的格式，不太能轻易转化到其它软件中。很显然，我们需要的是数据，是多年来保存下来的记录，而不是要被软件绑架的困境。

所以我一直谨慎寻找一个可用的，能彻底把数据放在用户自己手中的记账软件。如果可以，哪怕是能把EXCEL在线化私有化部署在网络上，我也觉得是极好的。

乱七八糟说了一堆，以上一点点个人的看法哈，再次谢谢作者大大~

**Comment by dingdangdog** [comment]
感谢使用和反馈。重新发布了一般，第一版BETA确实有点问题，[v1.0.0](https://github.com/dingdangdog/cashbook-desktop/releases/tag/1.0.0)应该可以正常安装使用。

您的反馈很用心，我会反复认真看的。

上一个仓库是以web应用的思路去开发的，所以主要是用的docker部署的。

这个仓库的初衷是开发一个在终端（个人设备）上独立运行的桌面程序（虽然目前本质上还是起了个服务）。

因为我觉得这类数据还是放在自己可控的机器上比较放心。如果想要把服务端（数据）放在外网服务器上也不是不行，还是比较简单的，后期其他问题优化完可以考虑单独做一版。

页面优化太难了。。。对于门外汉只能慢慢来了。。

**Comment by themis0009** [comment]
作者辛苦了。
我才是门外汉哈，虽然不愿意做伸手党，但是确实水平有限，对编程基本上一窍不通。
所以很多时候也就是动动嘴给个建议，具体是否可行，如何实行，都没法过过脑子。

因为数据丢怕了（我02年开始用账本软件，一开始是PC端的开天辟地，但是软件很快停止维护。后来08年改到移动端记账，中间零零散散用了好几款不同的，然而每次换软件都会伴随这丢失数据，实在是怕了），而厂商直接勾心斗角，都想要自己独占用户数据，增大别人的沉没成本。

所以个人设备是一个极好的想法，毕竟数据只有掌握在自己手中是最安全最放心的。

加油~~:)

**Comment by dingdangdog** [comment]
![image](https://github.com/dingdangdog/cashbook-desktop/assets/45959431/190bd630-6d64-4b68-a77c-d353e90cd57f)

![image](https://github.com/dingdangdog/cashbook-desktop/assets/45959431/10c7c60e-e972-4f21-b836-700218fe6c5e)


页面简单优化了一下，增加了字典管理、密钥修改，您可以看一下，欢迎提建议。

新代码导入导出功能还没有实现，实现后会发一版。

**Comment by dingdangdog** [comment]
已经发版[v1.0.1](https://github.com/dingdangdog/cashbook-desktop/releases/tag/1.0.1)，可下载试用，本issue就先关闭了
