### ISSUE TITLE
请问docker版本还维护吗？

### ISSUE THREAD

**Issue by sikenali** [dingdangdog/cashbook#11]
RT

**Comment by dingdangdog** [comment]
这个新仓库是为了应用桌面化，没有考虑docker部署。

有这个需求吗？想部署个web网站？

**Comment by sikenali** [comment]
> 这个新仓库是为了应用桌面化，没有考虑docker部署。
> 
> 有这个需求吗？想部署个web网站？

是的，看之前的仓库有docker版本，但是说不维护了，还能使用吗？

**Comment by dingdangdog** [comment]
可以使用，但是用起来可能不顺手。等我有空把新版本也封装个docker吧

**Comment by bfhh521** [comment]
> 这个新仓库是为了应用桌面化，没有考虑docker部署。
> 
> 有这个需求吗？想部署个web网站？

有的，可以比较方便部署在自己的服务器上私人使用。
同时如果能够进行家庭记账就更棒了，即多人同时使用同一个账本。

**Comment by dingdangdog** [comment]
> > 这个新仓库是为了应用桌面化，没有考虑docker部署。
> > 有这个需求吗？想部署个web网站？
> 
> 有的，可以比较方便部署在自己的服务器上私人使用。 同时如果能够进行家庭记账就更棒了，即多人同时使用同一个账本。

现在系统设计没有用户的概念，只有账本。只要有账本钥匙+可以访问系统，任何人都可以使用同一个账本。
近期会抽空整理个docker版本。感谢关注~

**Comment by bfhh521** [comment]
谢谢您的工作。

**Comment by dingdangdog** [comment]
临时发布了一个docker镜像，还有一些问题，由于水平限制和时间限制，暂时不知道咋解决。

> PS：虽然临时镜像有些问题，但经过一些操作也勉强能用，着急的可以自行尝试，详情可见：[1.0.4_docker](https://github.com/dingdangdog/cashbook-desktop/releases/tag/1.0.4_docker)

关闭issue
