### ISSUE TITLE
希望增加支持微信和支付宝的CSV账单信息

### ISSUE THREAD

**Issue by 59799517** [dingdangdog/cashbook#15]
希望增加支持微信和支付宝的CSV账单信息，每次手动录入太麻烦了

**Comment by dingdangdog** [comment]
收到，可以考虑一下。

**Comment by dingdangdog** [comment]
> 希望增加支持微信和支付宝的CSV账单信息，每次手动录入太麻烦了

其实前期有考虑过，因为我支付宝微信流水太杂了，直接导肯定也不行。所以要做的话，还得再仔细考虑一下。

**Comment by 59799517** [comment]
> > 希望增加支持微信和支付宝的CSV账单信息，每次手动录入太麻烦了
> 
> 其实前期有考虑过，因为我支付宝微信流水太杂了，直接导肯定也不行。所以要做的话，还得再仔细考虑一下。

还好呀前几行都是固定的，从固定行开始获取就可以 ， 要是支持原始带密码的压缩包就更好了，  在进一步支持邮箱自动识别就更方便了 ，有了新的账单识别出来页面输入密码即可导入  但是 邮箱信息毕竟是有些隐私的不支持也可以不影响

**Comment by dingdangdog** [comment]
> > > 希望增加支持微信和支付宝的CSV账单信息，每次手动录入太麻烦了
> > 
> > 
> > 其实前期有考虑过，因为我支付宝微信流水太杂了，直接导肯定也不行。所以要做的话，还得再仔细考虑一下。
> 
> 还好呀前几行都是固定的，从固定行开始获取就可以 ， 要是支持原始带密码的压缩包就更好了， 在进一步支持邮箱自动识别就更方便了 ，有了新的账单识别出来页面输入密码即可导入 但是 邮箱信息毕竟是有些隐私的不支持也可以不影响

emmmm，不是说格式杂，而是说数据杂，有些流水可能不想记录到账本中。。大概这样子。。。

**Comment by 59799517** [comment]
> mmm，不是说格式杂，而是说数据杂，有些流水可能不想记录到账本中。。大概这样子。。。

哦搜嘎  我要是会GO我都申请和你一起弄了 有flutter开发APP计划我可以帮忙

**Comment by GxxkX** [comment]
hhhh，我也正打算往这里面加呢

**Comment by 59799517** [comment]
> hhhh，我也正打算往这里面加呢

加好了吗 预算花超了。。急需支持

**Comment by dingdangdog** [comment]
> > hhhh，我也正打算往这里面加呢
> 
> 加好了吗 预算花超了。。急需支持

快了（开始考虑）

**Comment by dingdangdog** [comment]
> > hhhh，我也正打算往这里面加呢
> 
> 加好了吗 预算花超了。。急需支持

分析了一下支付宝的账单，处理起来有点复杂：
1. 收支类型目前本系统只应包含`支出`类记录；
2. 需要判断交易状态，有记录可能会是`交易关闭`；
3. 有些会发生退款；
4. 消费类型难以判断，如果需要该字段分析，还是需要手动填

本来想做个通用类的excel导入，发现也不实用（需要人工把excel维护好）。
正在考虑重构一下，便于拓展一些，所以Excel导入暂时搁置吧。
等重构差不多再考虑单独做一下吧。。。。

**Comment by dingdangdog** [comment]
支付宝手机和电脑导出的还不一样。。。

**Comment by dingdangdog** [comment]
新版本重构开发了支付宝和微信的csv账单导入功能，但需要大家提一些意见。本条ISSUE就关闭了。有意见或想法可以去新ISSUE中提出
新开ISSUE：https://github.com/dingdangdog/cashbook-desktop/issues/18
