### ISSUE TITLE
suggest: the best Integrated WeChat interface or alipay interface 🤪

### ISSUE THREAD

**Issue by zhovy** [dingdangdog/cashbook#23]

**Comment by dingdangdog** [comment]
Good idea, But, what interface? Like alipay, I just find [merchant bill download url](https://opendocs.alipay.com/open/759e0553_alipay.data.dataservice.bill.downloadurl.query). I think it's useless for general user, I don't know how do it for you suggest. 😢

**Comment by dingdangdog** [comment]
No ideas, close
