### ISSUE TITLE
微信账单导入有问题

### ISSUE THREAD

**Issue by jackjun001** [dingdangdog/cashbook#30]
有数据导入显示无数据
![1711804795024](https://github.com/dingdangdog/cashbook-desktop/assets/50038196/1d5a95f4-63db-4246-b810-2a8a2dd7071a)

**Comment by dingdangdog** [comment]
请问是哪个版本？建议用最新版。

然后建议文件导出的初始状态，不要改动，直接导入即可。使用`web`演示站试了下，没问题。

看起来是账单文件标题行不对，是微信导出的csv文件没动过吗？文件重要的两个参数：标题行、字符集编码。都是采用导出时的状态，所以不能改动。

默认是标题行应该是第17行，系统内计算是从0开始，所以显示的是16。

**Comment by jackjun001** [comment]
用的docker1.17版本，我刚刚用web演示是可以的，同一个文件

**Comment by dingdangdog** [comment]
> 用的docker1.17版本，我刚刚用web演示是可以的，同一个文件

演示站已经使用 `1.1.7` （目前的latest） 版本了

是 docker `0.1.17` 吗？？？emmmm，那个好像是重构前的版本，那时候应该没有微信导入吧。。。或者你想说的是 `1.1.7` ？

我用 `1.1.7` 试了一下，如果容器数据卷配置正确，我测试没有出现问题，如果配置错误解析数据会报错（`一般出现在历史配置没有修改`），但是没有发现你截图中的错误，截图中的错误看起来就是标题行不对：因为截图中的第一列数字像是一个时间数据，而不是一个正常的表头。

**`1.1.6` 以前的 `docker-compose.yml` 配置，升级到 `1.1.7` 需要手动做一下修改** ，详情可以见发布说明：[v1.1.7](https://github.com/dingdangdog/cashbook-desktop/releases/tag/v1.1.7)

下面是配置错误时的日志和截图：

```
Uncaught TypeError: Cannot read properties of null (reading '微信红包')
    at y (flowConvert-53fd955d.js:1:296)
    at f (flowConvert-53fd955d.js:1:425)
    at FlowExcelImport-d6e2ef7b.js:38:5891
    at Array.forEach (<anonymous>)
    at A.onload (FlowExcelImport-d6e2ef7b.js:38:5415)
```

![image](https://github.com/dingdangdog/cashbook-desktop/assets/45959431/c866aebb-5b75-4060-9fcc-e8d266fc288e)

**Comment by jackjun001** [comment]
问题解决了，的确是文件没有修改导致的，感谢
