### ISSUE TITLE
新增流水时选择了“支出”类型，下拉菜单中没有数据

### ISSUE THREAD

**Issue by smallcoderhujin** [dingdangdog/cashbook#32]
![1](https://github.com/dingdangdog/cashbook-desktop/assets/4199380/0e8bbf65-e91e-4707-8392-1265ba1a73f5)

支付方式和消费类型中都没有数据，在系统设置中看到有映射配置
容器日志中没有看到明显报错

**Comment by smallcoderhujin** [comment]
容器镜像版本：v1.1.7

**Comment by dingdangdog** [comment]
如果我没记错的话，手动新增流水时，支付方式和消费类型如果没有想要的，是可以输入的。

下个版本将提示内容“选择”改为“选择或输入”吧。感谢反馈。

**Comment by smallcoderhujin** [comment]
确实可以直接输入，找到了
