### ISSUE TITLE
感谢大佬~点个星

### ISSUE THREAD

**Issue by themis0009** [dingdangdog/cashbook#33]
做出私有化的账本。
能否帮忙增加一下功能：
1、修改账户密码。太复杂实在自己记不住。
2、修改支出类型。固定几个感觉覆盖不到。
3、增加管理员删除账本的功能。
4、稍微美化一下界面~
感谢大佬·

**Comment by dingdangdog** [comment]
感谢建议，近期可能会重写一个，还在思考，确定怎么弄之后会在这说一下~~

**Comment by dingdangdog** [comment]
> 做出私有化的账本。 能否帮忙增加一下功能： 1、修改账户密码。太复杂实在自己记不住。 2、修改支出类型。固定几个感觉覆盖不到。 3、增加管理员删除账本的功能。 4、稍微美化一下界面~ 感谢大佬·

新建了个桌面版仓库，目前临时发布了一般，仅支持windows，页面还和以前一样，后续会在新仓库慢慢优化：
https://github.com/dingdangdog/cashbook-desktop
