### ISSUE TITLE
类型映射生效

### ISSUE THREAD

**Issue by letsgo008** [dingdangdog/cashbook#34]
系统设置里面的类型映射修改完成后，什么时候生效？
建议有个刷新按钮，重新按照修改好的规则整理下数据。

**Comment by letsgo008** [comment]
类型映射是对那个字段生效？好想对备注字段没有效果。

<img width="1337" alt="image" src="https://github.com/dingdangdog/cashbook-desktop/assets/3468407/f50dda43-0c42-40cf-ac0c-54f69bd1bb52">

**Comment by dingdangdog** [comment]
> 系统设置里面的类型映射修改完成后，什么时候生效？ 建议有个刷新按钮，重新按照修改好的规则整理下数据。

我记得是立即生效呢。

类型映射是用来映射流水类型的，如餐饮、住宿等等这个类型，可以看Readme应该能明白：[类型映射](https://github.com/dingdangdog/cashbook-desktop?tab=readme-ov-file#%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84)

**Comment by letsgo008** [comment]
映射类型是不是对备注字段不生效的？

**Comment by dingdangdog** [comment]
> 类型映射是用来映射流水类型的

类型映射是用来映射流水列表中【`支出/收入类型`】该字段的，对其他字段均无效。1.1.8版本之前叫【`消费/收入类型`】。

**Comment by dingdangdog** [comment]
> > 类型映射是用来映射流水类型的
> 
> 类型映射是用来映射流水列表中【支出/收入类型】该字段的，对其他字段均无效。`1.1.8版本之前叫【消费/收入类型】`
