### ISSUE TITLE
类型映射升级后之前数据未保存

### ISSUE THREAD

**Issue by letsgo008** [dingdangdog/cashbook#38]
<img width="390" alt="image" src="https://github.com/dingdangdog/cashbook-desktop/assets/3468407/e5c3e6c1-25f9-4822-a07f-583821c02a4d">

类型映射数据当升级后，之前修改的被还原初始化了。该文件是否可以转出到/app/resources/app/data中，持久保存。

谢谢

**Comment by dingdangdog** [comment]
说得对！目前这个配置保存在了容器内的`config`文件夹，之前是想把`config`也保存到本地的，但是由于docker容器卷的一个问题，导致第一次部署时如果本地没有初始配置文件就没有默认值了。所以偷了个懒就没有将`config`保存到本地，等我思考一下有什么好办法解决没有。下个版本搞一下。
