### ISSUE TITLE
京东数据导入显示为空，无法导入

### ISSUE THREAD

**Issue by letsgo008** [dingdangdog/cashbook#39]
<img width="1345" alt="image" src="https://github.com/dingdangdog/cashbook-desktop/assets/3468407/b340f25e-0b14-4cc8-9774-2515c0f43b99">

1.1.8 版本

**Comment by dingdangdog** [comment]
有没有错误信息？标题行出现了说明文件解析没问题，但是为什么标题索引是 `0`，流水数量也是 `0`？目前能想到的只可能是数据某个字段有问题导致数据解析报错。F12看看有什么报错？

下面是我用演示站测试的，没有问题：

![image](https://github.com/dingdangdog/cashbook-desktop/assets/45959431/2dd2997d-0d1f-4352-8ace-e8b57ac889a3)

**Comment by letsgo008** [comment]
找到原因了。
macOS 系统中：1、用 safari 浏览器京东导入无法显示。2、 edge 浏览点击（支付宝、微信、京东）无法弹出选择文件界面。3、chrome 浏览器导入京东成功

**Comment by dingdangdog** [comment]
> 找到原因了。 macOS 系统中：1、用 safari 浏览器京东导入无法显示。2、 edge 浏览点击（支付宝、微信、京东）无法弹出选择文件界面。3、chrome 浏览器导入京东成功

这就厉害了，前端不是很懂，暂记一下吧。。。

**Comment by dingdangdog** [comment]
UI已经全新升级，此问题就关闭了，如果由用户发现新UI仍然出现该问题，可以提交一个新的ISSUE。
