### ISSUE TITLE
数据在线同步功能

### ISSUE THREAD

**Issue by dingdangdog** [dingdangdog/cashbook#4]
思考和设计数据在线同步功能：
1. 流水数据
2. 账本数据
3. 额度数据
4. 字典数据

该功能可分为上传和下载两个功能点。

**Comment by dingdangdog** [comment]
其他考虑：
1. 该功能作为导入、导出功能的升级版，无需用户手动导出导入，直接在线上传与下载即可
2. 为了节约服务器空间，上传的数据只保存30天或更短，后上传的数据会覆盖之前的数据
3. 用户需申请服务器密钥，上传和下载均需要密钥，每个密钥唯一对应一份数据
4. 提供删除云上数据的入口，用户可随时删除上传的数据

**Comment by dingdangdog** [comment]
是否考虑恢复记账本在线版本？

**Comment by oemsys** [comment]
安卓搞呀~？！安卓+桌面+WEB。哈哈老牛了~！

**Comment by dingdangdog** [comment]
> 坐等什么时间可以试用呀？

看情况吧，在线同步需要服务器，需要花钱搞，现在也没多少人用，所以没着急。

如果做出来用的人多了，可能会考虑收费的问题，毕竟服务器维护费用也不小。

**Comment by dingdangdog** [comment]
> 安卓搞呀~？！安卓+桌面+WEB。哈哈老牛了~！

多终端 前端技术点比较多，不是很擅长，所以搞起来会很慢。尽快吧

**Comment by oemsys** [comment]
> > 坐等什么时间可以试用呀？
> 
> 看情况吧，在线同步需要服务器，需要花钱搞，现在也没多少人用，所以没着急。
> 
> 如果做出来用的人多了，可能会考虑收费的问题，毕竟服务器维护费用也不小。

后端搞个DOCKER ~！~！给个地址配下服务地址跟端口。自己的数据自己搞。

**Comment by dingdangdog** [comment]
> > > 坐等什么时间可以试用呀？
> > 
> > 
> > 看情况吧，在线同步需要服务器，需要花钱搞，现在也没多少人用，所以没着急。
> > 如果做出来用的人多了，可能会考虑收费的问题，毕竟服务器维护费用也不小。
> 
> 后端搞个DOCKER ~！~！给个地址配下服务地址跟端口。自己的数据自己搞。

嗯，也不是不可以，只不过使用者需要一些技术了

**Comment by dingdangdog** [comment]
已经发布新版[v1.0.4](https://github.com/dingdangdog/cashbook-desktop/releases/tag/1.0.4)，支持在线数据同步功能，在线同步需要云服务的支持，公共云服务正在准备中……
