### ISSUE TITLE
windows客户端使用问题

### ISSUE THREAD

**Issue by smallcoderhujin** [dingdangdog/cashbook#40]
首先个人理解应用是使用docker在其他机器或者nas上部署了cachbook服务端，使用web直接访问或者windows客户端去连接并使用

疑问：
1. windows客户端上没有找到配置服务端地址的地方
2. 注册的时候，服务端是云端吗
3. 实际注册时无法使用，点击“注册”没有反应
![image](https://github.com/dingdangdog/cashbook-desktop/assets/4199380/53d917de-9874-43df-8229-872535d39f3d)

**Comment by dingdangdog** [comment]
Windows客户端是终端独立的，没有任何云端服务，会有后台exe程序作为http服务，数据也是保存在本机上的。

至于注册不能用就是另外的问题了，可能是exe没成功启动或接口报错之类的问题。

**Comment by dingdangdog** [comment]
发布了新版本[v1.1.9](https://github.com/dingdangdog/cashbook-desktop/releases/tag/v1.1.9)，测试了Windows版本注册也没有发现问题，所以关闭这个提问。
