### ISSUE TITLE
京东导入交易分类规则未生效

### ISSUE THREAD

**Issue by letsgo008** [dingdangdog/cashbook#41]
京东的导入，所有类型都是其他，是否对京东这部分规则没有生效？我看类型映射里有设置了。谢谢
<img width="554" alt="image" src="https://github.com/dingdangdog/cashbook-desktop/assets/3468407/cbc8d4d5-7c4b-4226-b2c1-db544405b8d8">

<img width="555" alt="image" src="https://github.com/dingdangdog/cashbook-desktop/assets/3468407/dd9db4d4-43f0-4246-a387-eb65ac5e786c">

<img width="630" alt="image" src="https://github.com/dingdangdog/cashbook-desktop/assets/3468407/530cb327-fa64-4951-a39e-33ce1771b1e8">

**Comment by letsgo008** [comment]
浏览器用的是 chrome，macos 系统

**Comment by letsgo008** [comment]
typeConvert(row[indexMap.get('交易分类')])
typeConvert(indexMap.get('交易分类'))

京东这里是不是漏了 row[]

**Comment by dingdangdog** [comment]
👍没错，你说的是对的
