### ISSUE TITLE
微信导入数据有误

### ISSUE THREAD

**Issue by hanielrui** [dingdangdog/cashbook#42]
超过1000的金额只会识别千位。
如¥1,020.00，导入后识别为1元。
![微信截图_20240613111750](https://github.com/dingdangdog/cashbook-desktop/assets/76834780/01beffe3-dff1-4996-bc42-d00f4d6ee976)

**Comment by hanielrui** [comment]
版本：docker v1.1.9  有此问题

在线体验：[cashbook.oldmoon.top](https://cashbook.oldmoon.top/) (体验账号：cashbook/cashbook)  有此问题

**Comment by dingdangdog** [comment]
请先排查是否存在文件问题。

比如使用记事本查看数据是否含有逗号`,` 即 `1,020.00`，如果有，可能是你使用excel或wps打开过文件导致的，这种情况无法从程序上解决。

**Comment by hanielrui** [comment]
试验发现确定是因为用excel打开过引起，已正常使用。
