### ISSUE TITLE
会增加对手机版网页的适配吗

### ISSUE THREAD

**Issue by qingkeee** [dingdangdog/cashbook#44]
昨天才发现这个，很轻量好用，部署方便，不用数据库好评。可惜目前手机端网页基本没办法用，ui都挤在一起了，希望大佬可能给手机网页做一下适配

**Comment by dingdangdog** [comment]
谢谢建议，在考虑做，还没想好

**Comment by dingdangdog** [comment]
从v3.0.1_BETA开始，使用全新UI，手机端做了一些适配优化，暂时只能做到这种程度了，可以访问 https://cashbook.oldmoon.top/ 上的最新版体验一下。

本issue关闭。

**Comment by qingkeee** [comment]
更新试了一下，可以的，手机这样算是能用了，辛苦。不用数据库真是太好了，换源更新的beta版，只需导入json就恢复了所有数据，
________________________________
发件人: dddx ***@***.***>
发送时间: 2024年9月22日 06:15
收件人: dingdangdog/cashbook ***@***.***>
抄送: qingkeee ***@***.***>; Author ***@***.***>
主题: Re: [dingdangdog/cashbook] 会增加对手机版网页的适配吗 (Issue #44)


从v3.0.1_BETA开始，使用全新UI，手机端做了一些适配优化，暂时只能做到这种程度了，可以访问 https://cashbook.oldmoon.top/ 上的最新版体验一下。

本issue关闭。

―
