### ISSUE TITLE
导入支付宝/微信/京东账单小建议

### ISSUE THREAD

**Issue by Daydreamer97** [dingdangdog/cashbook#45]
使用环境：Docker
发现问题：在“流水管理”页面重复导入同一份微信账单时，流水会被记两次
小建议：
1.可以评估一下：一次性导入多个csv账单文件的功能；
2.根据“交易定单号”信息做流水降重处理（目前看支付宝/微信/京东账单的导出文件，均有“交易订单号”信息。三家不知道能否统一去重，但是单一导入源应该能做去除重复流水的处理）；
3.可否在当前“消费日历”的基础上，新增“消费月历/消费年报”这种统一化的视图？

ps：
今天首次部署你的工程，个人感觉很好用，会继续使用下去，点赞！期待后续的优化！

**Comment by Daydreamer97** [comment]
翻了下之前的issues，看到也人提到流水降重的问题。我是首次使用，批量导入较多的账单，所以会关注到这个问题。但是其实也还好，一天两天，大差不差了。相对自己使用app“做假账”来说，数据准确度已经很高了哈哈哈哈

**Comment by dingdangdog** [comment]
感谢理解，已发布全新UI，历史问题就关闭了。关于此问题的更多对话请参考：#36
