### ISSUE TITLE
怎么使用呢

### ISSUE THREAD

**Issue by sjsunjiansj** [dingdangdog/cashbook#47]
docker部署了，新建账本后，提示没有数据
![image](https://github.com/user-attachments/assets/c570ff9f-bf1e-4939-8ded-62bf5c8ca877)
分类一直同步不了呢
![image](https://github.com/user-attachments/assets/910a5650-41f0-4331-b02c-53ec2d6f6453)
怎么添加数据呢，支付类型没有数据

**Comment by sjsunjiansj** [comment]
支付方式，和支付类型是必填得，但是两个在哪里设置呢。没有设置得地方

**Comment by sjsunjiansj** [comment]
![image](https://github.com/user-attachments/assets/229c4c1c-d37e-4392-abe9-5a9e97640cb8)

**Comment by dingdangdog** [comment]
新增流水时，如果没有要选择的选项，可以手动输入消费类型和支付方式。

另外，新版本3.0.1_beta已发布，可以尝试一下全新UI，个人感觉更好用一些。
