### ISSUE TITLE
能否做一个arm64的docker镜像，谢谢大佬

### ISSUE THREAD

**Issue by pythonmanGo** [dingdangdog/cashbook#52]

**Comment by dingdangdog** [comment]
好的，下次发版研究一下

**Comment by dingdangdog** [comment]
尝试构建了ARM架构的Docker镜像，可以试一试，我没测试。

DockerHub：[dingdangdog/cashbook:3.0.2-arm64](https://hub.docker.com/layers/dingdangdog/cashbook/3.0.2-arm64/images/sha256-cf1509e4f849ef55bf2aee8d7783d9282ba4681c379dca45a8094711cbcd402a?context=repo)

**Comment by SakuyaInory** [comment]
> 尝试构建了ARM架构的Docker镜像，可以试一试，我没测试。
> 
> DockerHub：[dingdangdog/cashbook:3.0.2-arm64](https://hub.docker.com/layers/dingdangdog/cashbook/3.0.2-arm64/images/sha256-cf1509e4f849ef55bf2aee8d7783d9282ba4681c379dca45a8094711cbcd402a?context=repo)

还好过来git看看，果然有arm的需求，zos使用没问题

**Comment by dingdangdog** [comment]
感谢反馈，此问题关闭
