### ISSUE TITLE
是否增加收费功能

### ISSUE THREAD

**Issue by dingdangdog** [dingdangdog/cashbook#8]
云服务器现在使用的是个人购买的服务器，运行维护成本较高，如果以后使用的人多了，在线同步的需求高了，一个服务器势必无法支撑功能正常运行。采用授权码收费的模式是否可行？

欢迎大家集思广益。

**Comment by GxxkX** [comment]
开源不能只靠用爱发电，我支持您在这一方面的想法

**Comment by dingdangdog** [comment]
再说吧，遥遥无期，到时候再来打开。

**Comment by wxyShine** [comment]
可以参考下这个  感觉很不错  https://github.com/anyant/rssant   付费使用官方提供的服务  或 自建使用
